name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Check Gradle Version
        run: |
          chmod +x gradlew
          ./gradlew --version
      - name: Check Gradle version
        run: |
          chmod +x gradlew
          ./gradlew --version
      - name: Test task with Gradle Wrapper
        run: |
          ./gradlew -i test
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          path: 'build/reports/tests/test'
          name: test-reports
          retention-days: 7